version: 1
directus: 11.1.0
vendor: sqlite
collections:
  - collection: clubs
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: clubs
      color: null
      display_template: null
      group: leagueData
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      preview_url: null
      singleton: false
      sort: 1
      sort_field: null
      translations: null
      unarchive_value: null
      versioning: false
    schema:
      name: clubs
  - collection: leagueData
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: leagueData
      color: null
      display_template: null
      group: null
      hidden: false
      icon: folder
      item_duplication_fields: null
      note: null
      preview_url: null
      singleton: false
      sort: 1
      sort_field: null
      translations: null
      unarchive_value: null
      versioning: false
  - collection: teams
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: teams
      color: null
      display_template: null
      group: leagueData
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      preview_url: null
      singleton: false
      sort: 2
      sort_field: null
      translations: null
      unarchive_value: null
      versioning: false
    schema:
      name: teams
  - collection: websiteContent
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: websiteContent
      color: null
      display_template: null
      group: null
      hidden: false
      icon: folder
      item_duplication_fields: null
      note: null
      preview_url: null
      singleton: false
      sort: 2
      sort_field: null
      translations: null
      unarchive_value: null
      versioning: false
fields:
  - collection: clubs
    field: id
    type: uuid
    meta:
      collection: clubs
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 1
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: id
      table: clubs
      data_type: char
      default_value: null
      max_length: 36
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: true
      is_primary_key: true
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: clubs
    field: dateCreated
    type: timestamp
    meta:
      collection: clubs
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: dateCreated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 2
      special:
        - cast-timestamp
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: dateCreated
      table: clubs
      data_type: datetime
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: clubs
    field: dateUpdated
    type: timestamp
    meta:
      collection: clubs
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: dateUpdated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 3
      special:
        - cast-timestamp
        - date-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: dateUpdated
      table: clubs
      data_type: datetime
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: clubs
    field: name
    type: string
    meta:
      collection: clubs
      conditions: null
      display: null
      display_options: null
      field: name
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: true
      sort: 4
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: name
      table: clubs
      data_type: varchar
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: clubs
    field: location
    type: string
    meta:
      collection: clubs
      conditions: null
      display: null
      display_options: null
      field: location
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: 5
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: location
      table: clubs
      data_type: varchar
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: teams
    field: id
    type: uuid
    meta:
      collection: teams
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 1
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: id
      table: teams
      data_type: char
      default_value: null
      max_length: 36
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: true
      is_primary_key: true
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: teams
    field: dateCreated
    type: timestamp
    meta:
      collection: teams
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: dateCreated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 2
      special:
        - cast-timestamp
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: dateCreated
      table: teams
      data_type: datetime
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: teams
    field: dateUpdated
    type: timestamp
    meta:
      collection: teams
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: dateUpdated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 3
      special:
        - cast-timestamp
        - date-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: dateUpdated
      table: teams
      data_type: datetime
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: teams
    field: name
    type: string
    meta:
      collection: teams
      conditions: null
      display: null
      display_options: null
      field: name
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: true
      sort: 4
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: name
      table: teams
      data_type: varchar
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: teams
    field: club
    type: string
    meta:
      collection: teams
      conditions: null
      display: null
      display_options: null
      field: club
      group: null
      hidden: false
      interface: select-dropdown-m2o
      note: null
      options:
        enableCreate: false
      readonly: false
      required: true
      sort: 5
      special:
        - m2o
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: club
      table: teams
      data_type: char
      default_value: null
      max_length: 36
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: clubs
      foreign_key_column: id
relations:
  - collection: teams
    field: club
    related_collection: clubs
    meta:
      junction_field: null
      many_collection: teams
      many_field: club
      one_allowed_collections: null
      one_collection: clubs
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    schema:
      table: teams
      column: club
      foreign_key_table: clubs
      foreign_key_column: id
      constraint_name: null
      on_update: NO ACTION
      on_delete: NO ACTION
